#
# registri pt un CHNT DDSU666 monofazat
#

esphome:
  name: modbus-smm
  friendly_name: modbus smm

  esp32:
    board: esp32dev
    framework:
      type: esp-idf

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "***************"

ota:
  - platform: esphome
    password: "****************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "modbus smm"
    password: "**********"

captive_portal:



uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  stop_bits: 1


modbus:
  id: mb

modbus_controller:
  - id: smm
    address: 1
    modbus_id: mb
    update_interval: 5s
    command_throttle: 100ms

sensor:
  # Register: 2000H
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Tensiune"
    id: "smm_tensiune"
    register_type: holding
    address: 0x2000
    value_type: FP32
    device_class: voltage
    unit_of_measurement: "V"

  # Register: 2002H
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Curent"
    id: "smm_curent"
    register_type: holding
    address: 0x2002
    value_type: FP32
    device_class: current
    unit_of_measurement: "A"

  # Register: 2004H
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Putere"
    id: "smm_putere"
    register_type: holding
    address: 0x2004
    value_type: FP32
    device_class: power
    unit_of_measurement: "kW"
    state_class: measurement

  # Register: 2006H
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Putere reactivă"
    id: "smm_putere_reactiva"
    register_type: holding
    address: 0x2006
    value_type: FP32
    device_class: reactive_power
    unit_of_measurement: "kvar"
    state_class: measurement

  # Register: 200AH
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Factor putere"
    id: "smm_factor_putere"
    register_type: holding
    address: 0x200A
    value_type: FP32
    device_class: power_factor

  # Register: 200EH
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Frecvență"
    id: "smm_frecventa"
    register_type: holding
    address: 0x200E
    value_type: FP32
    device_class: frequency
    unit_of_measurement: "Hz"

  # Register: 4000H
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Energie importată"
    id: "smm_energie_importata"
    register_type: holding
    address: 0x4000
    value_type: FP32
    device_class: energy
    unit_of_measurement: "kWh"
    state_class: total
    skip_updates: 60

  # Register: 400AH
  - platform: modbus_controller
    modbus_controller_id: smm
    name: "Energie exportată"
    id: "smm_energie_exportata"
    register_type: holding
    address: 0x400A
    value_type: FP32
    device_class: energy
    unit_of_measurement: "kWh"
    state_class: total
    skip_updates: 60